# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Shabbat_Project' do


source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'Google/SignIn'
pod 'GoogleMaps'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'MMDrawerController', '~> 0.6'
pod 'JSQMessagesViewController'
end

